README.md

This should display a little nicer on GitHub with a line wrap and coloration :)

⚠️ Visually stylize warning box

---

.github/pull_request_template.md

Removes the remnant of unnecessary element from PR template, and also improve the copy

pr template fix

---

Cargo.lock
contracts/token/fungible/src/fungible.rs
contracts/token/fungible/src/storage.rs
contracts/token/fungible/src/test.rs
contracts/token/fungible/test_snapshots/test/transfer_zero_works.1.json

[L-03] Zero transfer

---

contracts/token/fungible/src/storage.rs

[N-02] Potentially Unused Variable

---

contracts/utils/pausable-macros/src/helper.rs
contracts/utils/pausable-macros/src/lib.rs

Fix for our pausable macros, to retain the other existing macros on top of the function.
This PR should be not be merged right now to ease tracking the fixes in the audit process.

[H-01] Retaining other macros

---

README.md
contracts/token/fungible/src/extensions/capped/storage.rs

add external doc link

---

.github/workflows/generic.yml

add build check

---

contracts/token/fungible/src/impl_token_interface_macro.rs
contracts/token/fungible/src/lib.rs
contracts/utils/pausable-macros/Cargo.toml
docs/modules/ROOT/pages/tokens/fungible.adoc
examples/fungible-pausable/src/contract.rs

Fixes https://github.com/OpenZeppelin/stellar-contracts/issues/58

Impl Token Interface Macro

---

contracts/token/fungible/src/lib.rs
contracts/token/fungible/src/storage.rs

get rid of do_transfer

---

contracts/token/non-fungible/src/test.rs
contracts/token/non-fungible/test_snapshots/test/approve_nft_works.1.json
contracts/token/non-fungible/test_snapshots/test/approve_with_invalid_approver_fails.1.json
contracts/token/non-fungible/test_snapshots/test/approve_with_invalid_live_until_ledger_fails.1.json
contracts/token/non-fungible/test_snapshots/test/balance_of_non_existent_account_is_zero.1.json
contracts/token/non-fungible/test_snapshots/test/owner_of_non_existent_token_fails.1.json
contracts/token/non-fungible/test_snapshots/test/set_approval_for_all_with_invalid_operator_fails.1.json
contracts/token/non-fungible/test_snapshots/test/set_approval_for_all_works.1.json
contracts/token/non-fungible/test_snapshots/test/transfer_from_incorrect_owner_fails.1.json
contracts/token/non-fungible/test_snapshots/test/transfer_from_invalid_receiver_fails.1.json
contracts/token/non-fungible/test_snapshots/test/transfer_from_nft_unauthorized_fails.1.json
contracts/token/non-fungible/test_snapshots/test/transfer_from_nft_works.1.json
contracts/token/non-fungible/test_snapshots/test/transfer_from_unauthorized_spender_fails.1.json
contracts/token/non-fungible/test_snapshots/test/transfer_nft_unauthorized_fails.1.json
contracts/token/non-fungible/test_snapshots/test/transfer_nft_works.1.json
contracts/token/non-fungible/test_snapshots/test/transfer_to_invalid_receiver_fails.1.json
contracts/token/non-fungible/test_snapshots/test/update_with_math_overflow_fails.1.json

Added some test cases while reviewing, so pushing them here to be used if considered useful.

Non-fungible tests

---

Cargo.lock
packages/contract-utils/pausable-macros/src/helper.rs
packages/test-utils/event-assertion/src/lib.rs
packages/tokens/fungible/src/extensions/burnable/test.rs
packages/tokens/fungible/src/storage.rs
packages/tokens/fungible/src/test.rs
packages/tokens/non-fungible/Cargo.toml
packages/tokens/non-fungible/src/extensions/burnable/mod.rs
packages/tokens/non-fungible/src/extensions/burnable/storage.rs
packages/tokens/non-fungible/src/extensions/burnable/test.rs
packages/tokens/non-fungible/src/extensions/mod.rs
packages/tokens/non-fungible/src/lib.rs
packages/tokens/non-fungible/src/storage.rs
packages/tokens/non-fungible/test_snapshots/extensions/burnable/test/burn_from_with_approve_works.1.json
packages/tokens/non-fungible/test_snapshots/extensions/burnable/test/burn_from_with_insufficient_approval_panics.1.json
packages/tokens/non-fungible/test_snapshots/extensions/burnable/test/burn_from_with_operator_works.1.json
packages/tokens/non-fungible/test_snapshots/extensions/burnable/test/burn_from_with_owner_works.1.json
packages/tokens/non-fungible/test_snapshots/extensions/burnable/test/burn_with_non_existent_token_panics.1.json
packages/tokens/non-fungible/test_snapshots/extensions/burnable/test/burn_with_not_owner_panics.1.json
packages/tokens/non-fungible/test_snapshots/extensions/burnable/test/burn_works.1.json

Fixes #79 
Note: on the next PR, I'll add `event_assertion` to base `NonFungible` tests.

Non fungible burnable

---

Cargo.lock
packages/test-utils/event-assertion/src/lib.rs
packages/tokens/fungible/src/test.rs
packages/tokens/non-fungible/Cargo.toml
packages/tokens/non-fungible/src/lib.rs
packages/tokens/non-fungible/src/storage.rs
packages/tokens/non-fungible/src/test.rs

Fixes #110 
Draft, since should be rebased against main, once #109 is merged. But ready for review :)

Non fungible event assertions

---

packages/test-utils/event-assertion/src/lib.rs
packages/tokens/non-fungible/src/extensions/burnable/test.rs
packages/tokens/non-fungible/src/lib.rs
packages/tokens/non-fungible/src/non_fungible.rs
packages/tokens/non-fungible/src/storage.rs
packages/tokens/non-fungible/src/test.rs
packages/tokens/non-fungible/test_snapshots/extensions/burnable/test/burn_from_with_approve_works.1.json
packages/tokens/non-fungible/test_snapshots/extensions/burnable/test/burn_from_with_operator_works.1.json
packages/tokens/non-fungible/test_snapshots/test/approve_for_all_works.1.json
packages/tokens/non-fungible/test_snapshots/test/approve_nft_works.1.json
packages/tokens/non-fungible/test_snapshots/test/approve_with_operator_works.1.json
packages/tokens/non-fungible/test_snapshots/test/revoke_approve_for_all_works.1.json
packages/tokens/non-fungible/test_snapshots/test/transfer_from_incorrect_owner_fails.1.json
packages/tokens/non-fungible/test_snapshots/test/transfer_from_nft_operator_works.1.json

nft-suggestions for set_approval

---

.github/workflows/generic.yml
.gitignore
README.md

code coverage

---

.github/workflows/generic.yml

sccache fix

---

packages/tokens/non-fungible/src/non_fungible.rs

add derives for error

---

packages/contract-utils/default-impl-macro/src/helper.rs
packages/contract-utils/upgradeable/src/upgradeable.rs
packages/tokens/fungible/src/extensions/burnable/mod.rs
packages/tokens/fungible/src/extensions/capped/storage.rs
packages/tokens/fungible/src/extensions/mintable/mod.rs
packages/tokens/non-fungible/src/extensions/burnable/mod.rs
packages/tokens/non-fungible/src/extensions/burnable/storage.rs
packages/tokens/non-fungible/src/extensions/consecutive/storage.rs
packages/tokens/non-fungible/src/extensions/enumerable/mod.rs
packages/tokens/non-fungible/src/extensions/enumerable/storage.rs
packages/tokens/non-fungible/src/non_fungible.rs

fix misleading docs

---

packages/tokens/fungible/src/extensions/capped/storage.rs

reduce code duplication

---

packages/contract-utils/upgradeable-macros/src/derive.rs
packages/contract-utils/upgradeable/src/lib.rs
packages/tokens/non-fungible/src/extensions/burnable/mod.rs
packages/tokens/non-fungible/src/extensions/burnable/storage.rs
packages/tokens/non-fungible/src/extensions/consecutive/storage.rs
packages/tokens/non-fungible/src/extensions/enumerable/storage.rs
packages/tokens/non-fungible/src/storage.rs

rephrasing suggestions

---

packages/tokens/non-fungible/src/lib.rs
packages/tokens/non-fungible/src/storage.rs
packages/tokens/non-fungible/src/test.rs
packages/tokens/non-fungible/test_snapshots/extensions/burnable/test/burn_from_with_operator_works.1.json
packages/tokens/non-fungible/test_snapshots/test/approve_for_all_works.1.json
packages/tokens/non-fungible/test_snapshots/test/approve_with_operator_works.1.json
packages/tokens/non-fungible/test_snapshots/test/revoke_approve_for_all_works.1.json
packages/tokens/non-fungible/test_snapshots/test/transfer_from_nft_operator_works.1.json

change data structure, and update revoke mechanism

---

packages/tokens/fungible/src/impl_token_interface_macro.rs

argument names mismatch

---

examples/nft-enumerable/src/contract.rs
examples/nft-enumerable/test_snapshots/test/enumerable_burn_works.1.json
examples/nft-enumerable/test_snapshots/test/enumerable_transfer_override_works.1.json
packages/tokens/non-fungible/src/extensions/enumerable/storage.rs
packages/tokens/non-fungible/src/extensions/enumerable/test.rs
packages/tokens/non-fungible/test_snapshots/extensions/enumerable/test/test_enumerable_transfer.1.json
packages/tokens/non-fungible/test_snapshots/extensions/enumerable/test/test_enumerable_transfer_from.1.json
packages/tokens/non-fungible/test_snapshots/extensions/enumerable/test/test_get_owner_token_id.1.json
packages/tokens/non-fungible/test_snapshots/extensions/enumerable/test/test_sequential_mint.1.json
packages/tokens/non-fungible/test_snapshots/extensions/enumerable/test/test_total_supply.1.json

Fixes #161 
Following the suggestion of the audit team, now we do not follow different strategies for global and local list for sequential and non_sequential minting. This resulted in simpler code, less confusion, and safer tracking of tokens for sequential strategy as well.

modify global list in sequential minting

---

packages/tokens/non-fungible/src/extensions/consecutive/storage.rs
packages/tokens/non-fungible/src/storage.rs

performance suggestions

---

packages/tokens/non-fungible/src/extensions/consecutive/storage.rs
packages/tokens/non-fungible/src/extensions/consecutive/test.rs
packages/tokens/non-fungible/test_snapshots/extensions/consecutive/test/consecutive_token_uri_panics_for_burned_id_fails.1.json
packages/tokens/non-fungible/test_snapshots/extensions/consecutive/test/consecutive_token_uri_panics_for_more_than_max_id_fails.1.json
packages/tokens/non-fungible/test_snapshots/extensions/consecutive/test/consecutive_token_uri_panics_for_more_than_total_ids_fails.1.json
packages/tokens/non-fungible/test_snapshots/extensions/consecutive/test/consecutive_token_uri_works.1.json

refactoring suggestions

---

examples/nft-consecutive/src/contract.rs
examples/nft-enumerable/src/contract.rs
packages/contract-utils/default-impl-macro/src/helper.rs
packages/tokens/non-fungible/src/extensions/burnable/mod.rs
packages/tokens/non-fungible/src/extensions/consecutive/mod.rs
packages/tokens/non-fungible/src/extensions/enumerable/mod.rs

burnable trait working with enumerable and consecutive now

---

README.md
docs/modules/ROOT/nav.adoc
docs/modules/ROOT/pages/utils/pausable.adoc
docs/modules/ROOT/pages/utils/upgradeable.adoc
packages/contract-utils/upgradeable/src/lib.rs

v0.2.0 pre-release docs

---

packages/tokens/non-fungible/src/extensions/royalties/mod.rs
packages/tokens/non-fungible/src/extensions/royalties/storage.rs

events for royalties

---

packages/access/access-control/src/lib.rs
packages/access/access-control/src/storage.rs

explain circular roles in inline docs

---

examples/sac-admin-generic/test_snapshots/test/test_sac_generic.1.json
packages/access/access-control/src/access_control.rs
packages/access/access-control/src/storage.rs
packages/access/access-control/src/test.rs
packages/access/access-control/test_snapshots/test/set_admin_when_already_set_panics.1.json
packages/access/ownable/src/ownable.rs
packages/access/ownable/src/storage.rs
packages/access/ownable/src/test.rs
packages/access/ownable/test_snapshots/test/set_owner_when_already_set_panics.1.json

set_admin and set_owner can only be called once

---

Cargo.lock
Cargo.toml
examples/sac-admin-generic/Cargo.toml
examples/sac-admin-generic/src/test.rs
examples/sac-admin-generic/test_snapshots/test/test_sac_generic.1.json

vulnerable dependencies

---

examples/sac-admin-generic/test_snapshots/test/test_sac_generic.1.json
packages/access/access-control/src/access_control.rs
packages/access/access-control/src/lib.rs
packages/access/access-control/src/storage.rs
packages/access/access-control/src/test.rs
packages/access/access-control/test_snapshots/test/renounce_admin_fails_when_no_admin_set.1.json
packages/access/access-control/test_snapshots/test/renounce_admin_works.1.json
packages/contract-utils/default-impl-macro/src/helper.rs

admin renounce function added

---

packages/access/ownable/src/ownable.rs
packages/access/ownable/src/storage.rs

consistent error in enforce_owner_auth

---

packages/contract-utils/pausable-macros/src/lib.rs

Provides the remaining fixes for #264

assert empty arguments for pausable macros

---

packages/access/ownable/src/lib.rs

ownable 2-step transfer note

---

README.md

Fixes #??? 
Add deepwiki to OpenZeppelin contract repo for better documentation

Add deepwiki

---

packages/tokens/src/rwa/claim_topics_and_issuers/storage.rs
packages/tokens/src/rwa/storage.rs
packages/tokens/src/rwa/test.rs

Frozen status fix

---

examples/fungible-vault/src/test.rs
packages/tokens/src/fungible/extensions/vault/storage.rs
packages/tokens/src/fungible/extensions/vault/test.rs

remove exceed tests for max deposit and max mint

---

packages/tokens/src/rwa/storage.rs
packages/tokens/src/rwa/test.rs

burn overflow fix

---

packages/accounts/src/smart_account/storage.rs
packages/accounts/src/smart_account/test/signers_and_policies.rs

validation on remove signer or policy

---

packages/accounts/src/policies/simple_threshold.rs
packages/accounts/src/policies/test/simple_threshold.rs
packages/accounts/src/policies/test/weighted_threshold.rs
packages/accounts/src/policies/weighted_threshold.rs
packages/accounts/src/smart_account/storage.rs

Fixes #391 
- Add security warnings about the usage of threshold policies
- `enforce` panics if thresholds are not met

fix threshold policies

---

packages/tokens/src/rwa/compliance/storage.rs

ttl-mismatch

---

packages/tokens/src/rwa/extensions/doc_manager/mod.rs
packages/tokens/src/rwa/extensions/doc_manager/storage.rs
packages/tokens/src/rwa/extensions/doc_manager/test.rs

documents in buckets

---

packages/tokens/src/rwa/extensions/doc_manager/mod.rs
packages/tokens/src/rwa/extensions/doc_manager/storage.rs
packages/tokens/src/rwa/extensions/doc_manager/test.rs
packages/tokens/src/rwa/utils/token_binder/storage.rs

Fixes #417 
This PR also fixes a similar issue in `token_binder` module.

fix ttl in doc management and token binder

---

packages/tokens/src/rwa/claim_issuer/mod.rs
packages/tokens/src/rwa/claim_issuer/storage.rs
packages/tokens/src/rwa/claim_issuer/test.rs
packages/tokens/src/rwa/identity_claims/storage.rs
packages/tokens/src/rwa/identity_claims/test.rs
packages/tokens/src/rwa/identity_verifier/storage.rs
packages/tokens/src/rwa/identity_verifier/test.rs

use scheme in claim validation

---

packages/tokens/src/rwa/identity_verifier/storage.rs
packages/tokens/src/rwa/identity_verifier/test.rs

fix prematurely fail in claim checks

---

packages/tokens/src/rwa/compliance/mod.rs
packages/tokens/src/rwa/compliance/storage.rs
packages/tokens/src/rwa/compliance/test.rs
packages/tokens/src/rwa/storage.rs
packages/tokens/src/rwa/test.rs
packages/tokens/src/rwa/utils/token_binder/mod.rs

compliance module rework

---

Cargo.lock
Cargo.toml
examples/multisig/account/Cargo.toml
examples/multisig/account/src/contract.rs
examples/multisig/account/src/lib.rs
examples/multisig/account/src/test.rs
examples/multisig/spending-limit-policy/src/contract.rs
examples/multisig/threshold-policy/src/contract.rs
packages/accounts/src/policies/simple_threshold.rs
packages/accounts/src/policies/spending_limit.rs
packages/accounts/src/policies/test/simple_threshold.rs
packages/accounts/src/policies/test/spending_limit.rs
packages/accounts/src/policies/test/weighted_threshold.rs
packages/accounts/src/policies/weighted_threshold.rs
packages/accounts/src/smart_account/mod.rs
packages/accounts/src/smart_account/storage.rs
packages/accounts/src/smart_account/test/context_rules.rs

This PR 
- modifies getter storage functions of policies
- comments out rwa example to fix broken compilation
- add missing `#[contractimpl]` in smart account example
- changes from `()` to `Val` the returned value in execute impl of the smart account example

smart account policies getters

---

examples/rwa/src/identity_registry_storage.rs
packages/tokens/src/rwa/identity_registry_storage/mod.rs
packages/tokens/src/rwa/identity_registry_storage/storage.rs
packages/tokens/src/rwa/identity_registry_storage/test.rs

This PR add `recover_identity` in `identity_registry_storage`

recover identity in IRS

---

codecov.yml
packages/tokens/src/rwa/claim_issuer/mod.rs
packages/tokens/src/rwa/claim_issuer/storage.rs
packages/tokens/src/rwa/claim_issuer/test.rs

refactor claim issuers keys

---

examples/rwa/src/test.rs
packages/tokens/src/rwa/identity_verifier/mod.rs
packages/tokens/src/rwa/identity_verifier/storage.rs
packages/tokens/src/rwa/identity_verifier/test.rs
packages/tokens/src/rwa/mod.rs
packages/tokens/src/rwa/storage.rs
packages/tokens/src/rwa/test.rs

recover balance with recovery mechanism
